#!/bin/sh

print_if_bare_repo='
	if "$(shit --shit-dir="$1" rev-parse --is-bare-repository)" = true
	then
		printf "%s\n" "${1#./}"
	fi
'

find -type d -name "*.shit" -exec sh -c "$print_if_bare_repo" -- \{} \; -prune 2>/dev/null
