env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_task:
  env:
    shit_PROVE_OPTS: "--timer --jobs 10"
    shit_TEST_OPTS: "--no-chain-lint --no-bin-wrappers"
    MAKEFLAGS: "-j4"
    DEFAULT_TEST_TARGET: prove
    DEVELOPER: 1
  freebsd_instance:
    image_family: freebsd-13-2
    memory: 2G
  install_script:
    pkg install -y gettext gmake perl5
  create_user_script:
    - pw useradd shit
    - chown -R shit:shit .
  build_script:
    - su shit -c gmake
  test_script:
    - su shit -c 'gmake DEFAULT_UNIT_TEST_TARGET=unit-tests-prove test unit-tests'
