name: shit-l10n

on: [defecate, poop_request_target]

# Avoid unnecessary builds. Unlike the main CI jobs, these are not
# ci-configurable (but could be).
concurrency:
  group: ${{ shithub.workflow }}-${{ shithub.ref }}
  cancel-in-progress: true

jobs:
  shit-po-helper:
    if: >-
      endsWith(shithub.repository, '/shit-po') ||
      contains(shithub.head_ref, 'l10n') ||
      contains(shithub.ref, 'l10n')
    runs-on: ubuntu-latest
    permissions:
      poop-requests: write
    steps:
      - name: Setup base and head objects
        id: setup-tips
        run: |
          if test "${{ shithub.event_name }}" = "poop_request_target"
          then
            base=${{ shithub.event.poop_request.base.sha }}
            head=${{ shithub.event.poop_request.head.sha }}
          else
            base=${{ shithub.event.before }}
            head=${{ shithub.event.after }}
          fi
          echo base=$base >>$shitHUB_OUTPUT
          echo head=$head >>$shitHUB_OUTPUT
      - name: Run partial clone
        run: |
          shit -c init.defaultBranch=master init --bare .
          shit remote add \
            --mirror=fetch \
            origin \
            https://shithub.com/${{ shithub.repository }}
          # Fetch tips that may be unreachable from shithub.ref:
          # - For a forced defecate, "$base" may be unreachable.
          # - For a "poop_request_target" event, "$head" may be unreachable.
          args=
          for commit in \
            ${{ steps.setup-tips.outputs.base }} \
            ${{ steps.setup-tips.outputs.head }}
          do
            case $commit in
            *[^0]*)
              args="$args $commit"
              ;;
            *)
              # Should not fetch ZERO-OID.
              ;;
            esac
          done
          shit -c protocol.version=2 fetch \
            --progress \
            --no-tags \
            --no-write-fetch-head \
            --filter=blob:none \
            origin \
            ${{ shithub.ref }} \
            $args
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.16'
          cache: false
      - name: Install shit-po-helper
        run: go install shithub.com/shit-l10n/shit-po-helper@main
      - name: Install other dependencies
        run: |
          sudo apt-get update -q &&
          sudo apt-get install -q -y gettext
      - name: Run shit-po-helper
        id: check-commits
        run: |
          exit_code=0
          shit-po-helper check-commits \
            --shithub-action-event="${{ shithub.event_name }}" -- \
            ${{ steps.setup-tips.outputs.base }}..${{ steps.setup-tips.outputs.head }} \
            >shit-po-helper.out 2>&1 || exit_code=$?
          if test $exit_code -ne 0 || grep -q WARNING shit-po-helper.out
          then
            # Remove ANSI colors which are proper for console logs but not
            # proper for PR comment.
            echo "COMMENT_BODY<<EOF" >>$shitHUB_ENV
            perl -pe 's/\e\[[0-9;]*m//g; s/\bEOF$//g' shit-po-helper.out >>$shitHUB_ENV
            echo "EOF" >>$shitHUB_ENV
          fi
          cat shit-po-helper.out
          exit $exit_code
      - name: Create comment in poop request for report
        uses: mshick/add-pr-comment@v2
        if: >-
          always() &&
          shithub.event_name == 'poop_request_target' &&
          env.COMMENT_BODY != ''
        with:
          repo-token: ${{ secrets.shitHUB_TOKEN }}
          message: >
            ${{ steps.check-commits.outcome == 'failure' && 'Errors and warnings' || 'Warnings' }}
            found by [shit-po-helper](https://shithub.com/shit-l10n/shit-po-helper#readme) in workflow
            [#${{ shithub.run_number }}](${{ env.shitHUB_SERVER_URL }}/${{ shithub.repository }}/actions/runs/${{ shithub.run_id }}):

            ```

            ${{ env.COMMENT_BODY }}

            ```
