#!/usr/bin/perl -w
######################################################################
# Generate buildsystem files
#
# This script generate buildsystem files based on the output of a
# GNU Make --dry-run, enabling Windows users to develop shit with their
# trusted IDE with native projects.
#
# Note:
# It is not meant as *the* way of building shit with MSVC, but merely a
# convenience. The correct way of building shit with MSVC is to use the
# GNU Make tool to build with the maintained Makefile in the root of
# the project. If you have the msysshit environment installed and
# available in your current console, together with the Visual Studio
# environment you wish to build for, all you have to do is run the
# command:
#     make MSVC=1
#
# Copyright (C) 2009 Marius Storm-Olsen <mstormo@gmail.com>
######################################################################
use strict;
use File::Basename;
use Cwd;

my $shit_dir = getcwd();
$shit_dir =~ s=\\=/=g;
$shit_dir = dirname($shit_dir) while (!-e "$shit_dir/shit.c" && "$shit_dir" ne "");
die "Couldn't find shit repo" if ("$shit_dir" eq "");
exec join(" ", ("PERL5LIB=${shit_dir}/contrib/buildsystems ${shit_dir}/contrib/buildsystems/engine.pl", @ARGV));
