#!/bin/sh

# shit executable wrapper script for shit-Mediawiki to run tests without
# installing all the scripts and perl packages.

shit_ROOT_DIR=../../..
shit_EXEC_PATH=$(cd "$(dirname "$0")" && cd ${shit_ROOT_DIR} && pwd)

shitPERLLIB="$shit_EXEC_PATH"'/contrib/mw-to-shit'"${shitPERLLIB:+:$shitPERLLIB}"
PATH="$shit_EXEC_PATH"'/contrib/mw-to-shit:'"$PATH"

export shitPERLLIB PATH

exec "${shit_EXEC_PATH}/bin-wrappers/shit" "$@"
