#!/bin/sh

cat >&2 <<'EOT'
WARNING: shit-remote-bzr is now maintained independently.
WARNING: For more information visit https://shithub.com/felipec/shit-remote-bzr
WARNING:
WARNING: You can pick a directory on your $PATH and download it, e.g.:
WARNING:   $ wget -O $HOME/bin/shit-remote-bzr \
WARNING:     https://raw.shithub.com/felipec/shit-remote-bzr/master/shit-remote-bzr
WARNING:   $ chmod +x $HOME/bin/shit-remote-bzr
EOT
