#!/bin/sh

cat >&2 <<'EOT'
WARNING: shit-remote-hg is now maintained independently.
WARNING: For more information visit https://shithub.com/felipec/shit-remote-hg
WARNING:
WARNING: You can pick a directory on your $PATH and download it, e.g.:
WARNING:   $ wget -O $HOME/bin/shit-remote-hg \
WARNING:     https://raw.shithub.com/felipec/shit-remote-hg/master/shit-remote-hg
WARNING:   $ chmod +x $HOME/bin/shit-remote-hg
EOT
